export const featuredImages = [
  {
    src: '/images/featuredi.png',
    alt: 'Featured image 1',
    width: 381,
    height: 263
  },
  {
    src: '/images/featuredii.png',
    alt: 'Featured image 2',
    width: 381,
    height: 263
  },
  {
    src: '/images/featurediii.png',
    alt: 'Featured image 3',
    width: 381,
    height: 263
  },
  {
    src: '/images/featurediv.png',
    alt: 'Featured image 4',
    width: 381,
    height: 263
  },
]

export const savedList = [
  {
    image: '/images/viewedi.png',
    date: '27 April, 2023',
    title: 'Digital marketing made simple',
    podcaster: 'Julie Morgan',
    length: '30 Min',
    link: '/saved-list'
  },
  {
    image: '/images/featuredi.png',
    date: '27 April, 2023',
    title: 'Design details',
    podcaster: 'George Brian',
    length: '15 Min',
    link: '/saved-list'
  },
  {
    image: '/images/viewediv.png',
    date: '8 June, 2023',
    title: 'Art of Cryptocurrency',
    podcaster: 'Enoch Timothy',
    length: '1 hour',
    link: '/saved-list'
  },
]

export const guestList = [
  {
    image: '/images/viewedi.png',
    title: 'Digital marketing made simple',
    podcaster: 'Julie Morgan',
  },
  {
    image: '/images/viewediii.png',
    title: 'Design details',
    podcaster: 'George Brian',
  },
  {
    image: '/images/viewedviii.png',
    title: 'Art of Cryptocurrency',
    podcaster: 'Enoch Timothy',
  },
  {
    image: '/images/viewedii.png',
    title: 'Communication',
    podcaster: 'Anne Rice',
  },
  {
    image: '/images/viewedv.png',
    title: 'Interviews and more',
    podcaster: 'The Crew',
  },
  {
    image: '/images/viewedix.png',
    title: 'Relationship matters',
    podcaster: 'Jane Brayan',
  },
  {
    image: '/images/viewedVii.png',
    title: 'Entertainment: Music and Movies',
    podcaster: 'Frank B. Stones',
  },
  {
    image: '/images/viewedvi.png',
    title: 'Interviews and more',
    podcaster: 'John and June',
  },
  {
    image: '/images/viewediv.png',
    title: 'Discoveries',
    podcaster: 'Personalised Discovery',
  },
]

export const podcastList = [
  {
    image: '/images/viewedi.png',
    title: 'Digital marketing made simple',
    podcaster: 'Julie Morgan',
  },
  {
    image: '/images/viewediii.png',
    title: 'Design details',
    podcaster: 'George Brian',
  },
  {
    image: '/images/viewedviii.png',
    title: 'Art of Cryptocurrency',
    podcaster: 'Enoch Timothy',
  },
  {
    image: '/images/viewedii.png',
    title: 'Communication',
    podcaster: 'Anne Rice',
  },
  {
    image: '/images/viewedv.png',
    title: 'Interviews and more',
    podcaster: 'The Crew',
  },
  {
    image: '/images/viewedix.png',
    title: 'Relationship matters',
    podcaster: 'Jane Brayan',
  },
  {
    image: '/images/viewedVii.png',
    title: 'Entertainment: Music and Movies',
    podcaster: 'Frank B. Stones',
  },
  {
    image: '/images/viewedvi.png',
    title: 'Interviews and more',
    podcaster: 'John and June',
  },
  {
    image: '/images/viewediv.png',
    title: 'Discoveries',
    podcaster: 'Personalised Discovery',
  },
]

export const dropdown_options = [{ option: 'Location 1' }, { option: 'Location 2' }, { option: 'Location 3' }, { option: 'Location 4' }]

export const gender_options = [{ option: '' }, { option: 'Male' }, { option: 'Female' }, { option: 'Non-Binary' }, { option: 'Prefer not to say' }]

export const new_options = [{ option: '' }, { option: 'New' }, { option: 'Featured' }]

export const category_options = [
  { option: '' },
  { option: 'Arts' },
  { option: 'Business' },
  { option: 'Comedy' },
  { option: 'Education' },
  { option: 'Fiction' },
  { option: 'Finance' },
  { option: 'Government' },
  { option: 'History' },
  { option: 'Health & Fitness' },
  { option: 'Kids & Family' },
  { option: 'Leisure' },
  { option: 'Music' },
  { option: 'News' },
  { option: 'Religion & Spirituality' },
  { option: 'Science' },
  { option: 'Society & Culture' },
  { option: 'Sports' },
  { option: 'Technology' },
  { option: 'True Crime' },
  { option: 'TV & Film' }
]

export const age_options = [
  { option: '' },
  { option: '18-25 years old' },
  { option: '26-30 years old' },
  { option: '30-45 years old' },
  { option: '45 and above years old' }
]


export const language_options = [
  { option: '' },
  { option: 'English' },
  { option: 'Afrikaans' },
  { option: 'Albanian' },
  { option: 'Amharic' },
  { option: 'Arabic' },
  { option: 'Armenian' },
  { option: 'Assamese' },
  { option: 'Aymara' },
  { option: 'Azerbaijani' },
  { option: 'Bambara' },
  { option: 'Basque' },
  { option: 'Belarusian' },
  { option: 'Bengali' },
  { option: 'Bhojpuri' },
  { option: 'Bosnian' },
  { option: 'Bulgarian' },
  { option: 'Catalan' },
  { option: 'Cebuano' },
  { option: 'Chinese' },
  { option: 'Corsican' },
  { option: 'Croatian' },
  { option: 'Czech' },
  { option: 'Danish' },
  { option: 'Dhivehi' },
  { option: 'Dogri' },
  { option: 'Dutch' },
  { option: 'Esperanto' },
  { option: 'Estonian' },
  { option: 'Ewe' },
  { option: 'Filipino' },
  { option: 'Finnish' },
  { option: 'French' },
  { option: 'Frisian' },
  { option: 'Galician' },
  { option: 'Georgian' },
  { option: 'German' },
  { option: 'Greek' },
  { option: 'Guarani' },
  { option: 'Gujarati' },
  { option: 'Haitian Creole' },
  { option: 'Hausa' },
  { option: 'Hawaiian' },
  { option: 'Hebrew' },
  { option: 'Hindi' },
  { option: 'Hmong' },
  { option: 'Hungarian' },
  { option: 'Icelandic' },
  { option: 'Igbo' },
  { option: 'Ilocano' },
  { option: 'Indonesian' },
  { option: 'Irish' },
  { option: 'Italian' },
  { option: 'Japanese' },
  { option: 'Javanese' },
  { option: 'Kannada' },
  { option: 'Kazakh' },
  { option: 'Khmer' },
  { option: 'Kinyarwanda' },
  { option: 'Konkani' },
  { option: 'Korean' },
  { option: 'Krio' },
  { option: 'Kurdish' },
  { option: 'Kyrgyz' },
  { option: 'Lao' },
  { option: 'Latin' },
  { option: 'Latvian' },
  { option: 'Lingala' },
  { option: 'Lithuanian' },
  { option: 'Luganda' },
  { option: 'Luxembourgish' },
  { option: 'Macedonian' },
  { option: 'Maithili' },
  { option: 'Malagasy' },
  { option: 'Malay' },
  { option: 'Malayalam' },
  { option: 'Maltese' },
  { option: 'Maori' },
  { option: 'Marathi' },
  { option: 'Meiteilon' },
  { option: 'Mizo' },
  { option: 'Mongolian' },
  { option: 'Myanmar' },
  { option: 'Nepali' },
  { option: 'Norwegian' },
  { option: 'Nyanja' },
  { option: 'Odia' },
  { option: 'Oromo' },
  { option: 'Pashto' },
  { option: 'Persian' },
  { option: 'Polish' },
  { option: 'Portuguese' },
  { option: 'Punjabi' },
  { option: 'Romanian' },
  { option: 'Russian' },
  { option: 'Samoan' },
  { option: 'Sanskrit' },
  { option: 'Scots Gaelic' },
  { option: 'Sepedi' },
  { option: 'Serbian' },
  { option: 'Sesotho' },
  { option: 'Shona' },
  { option: 'Sindhi' },
  { option: 'Sinhala' },
  { option: 'Slovak' },
  { option: 'Slovenian' },
  { option: 'Somali' },
  { option: 'Spanish' },
  { option: 'Sundanese' },
  { option: 'Swahili' },
  { option: 'Swedish' },
  { option: 'Tagalog' },
  { option: 'Tamil' },
  { option: 'Tatar' },
  { option: 'Telugu' },
  { option: 'Thai' },
  { option: 'Tigrinya' },
  { option: 'Tsonga' },
  { option: 'Turkish' },
  { option: 'Turkmen' },
  { option: 'Twi' },
  { option: 'Ukrainian' },
  { option: 'Urdu' },
  { option: 'Uyghur' },
  { option: 'Uzbek' },
  { option: 'Vietnamese' },
  { option: 'Welsh' },
  { option: 'Xhosa' },
  { option: 'Yiddish' },
  { option: 'Yoruba' },
  { option: 'Zulu' }
]
